Remove troubleshooting code

diff --git a/etc/cont-init.d/02-firstrun b/etc/cont-init.d/02-firstrun
--- a/etc/cont-init.d/02-firstrun
+++ b/etc/cont-init.d/02-firstrun
@@ -261,8 +261,6 @@ curl "http://127.0.0.1/install/${NEXTLOCATION}" \
 while :
 do
 
-  date
-
   # Get JSON status of install, output to temp file
   curl 'http://127.0.0.1/install/install-action.php' \
     --silent \
@@ -275,18 +273,16 @@ do
     -H 'Connection: keep-alive' \
     --cookie-jar /tmp/install_process_cookies > /tmp/install_process_status_json
 
-  date
-
-  # check to make sure the json is valid
-  if ! jq "." < /tmp/install_process_status_json > /dev/null 2>&1; then
-    echo ""
-    echo -e "${YELLOW}WARNING: Invalid JSON returned:${NOCOLOR}"
-    cat /tmp/install_process_status_json
-    echo ""
-    echo -e "${YELLOW}Attempting to continue...${NOCOLOR}"
-    echo ""
-    break
-  fi
+  # # check to make sure the json is valid
+  # if ! jq "." < /tmp/install_process_status_json > /dev/null 2>&1; then
+  #   echo ""
+  #   echo -e "${YELLOW}WARNING: Invalid JSON returned:${NOCOLOR}"
+  #   cat /tmp/install_process_status_json
+  #   echo ""
+  #   echo -e "${YELLOW}Attempting to continue...${NOCOLOR}"
+  #   echo ""
+  #   break
+  # fi
 
   # Get info from json
   INSTALLERROR=$(jq ".error" < /tmp/install_process_status_json)
